### ISSUE TITLE
L'utilisation du widget génère une erreur 500

### ISSUE THREAD

**Issue by julmud** [franck-paul/mymeta#2]
Environnement : Dotclear 2.24.1 / PHP 7.4.33 / mymeta 1.2

J'ai installé MyMeta sur un de mes blogs et ai créé une nouvelle métadonnées de type Liste avec une dizaine de valeurs. Lorsque je souhaite afficher ces métadonnées sur la partie du publique du blog avec un widget, j'obtiens une erreur 500 :
```
[22-Jan-2023 07:48:07 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method dcMeta::getMeta() in /.../dcplugins/mymeta/_public.php:312
Stack trace:
#0 /.../dotclear/plugins/widgets/inc/widgets.php(321): widgetsMyMeta::mymetaValues(Object(dcWidget), 4)
#1 /.../dotclear/plugins/widgets/inc/public.tpl.php(72): dcWidget->call(4)
#2 /.../dotclear/cache/cbtpl/9c/f3/9cf3167591cb5965acc5ca177c099076.php(10): publicWidgets::widgetsHandler('nav', Array)
#3 /.../dotclear/inc/libs/clearbricks/template/class.template.php(496): include('/.../...')
#4 /.../dotclear/inc/public/class.dc.template.php(246): template->getData('_sidebar.html')
#5 /.../dotclear/cache/cbtpl/67/69/67697cdbad5ea03cbc5e9d0f8bb671e2.php(371): dcTemplate->getData('_sidebar.html')
#6 /.../dotclear/inc/libs/clearbricks/template/class.template.php(496): include('/.../...')
#7 /.../dotclear/inc/ in /.../dcplugins/mymeta/_public.php on line 312
```

La configuration du widget est la suivante :
* Mode d'affichage : liste
* Limite : 20
* Trier par : Nombre de billets
* Ordre : croissant

**Comment by franck-paul** [comment]
Va falloir prévoir un certain délai parce que la nomenclature utilisée dans ce code n'est pas logique (id = type, value = id, …)

Et je n'ai pas d'info (commentaire dans le code) sur ce qui est attendu. Donc il va falloir faire du reverse-engineering…

**Comment by julmud** [comment]
Je comprends. Bon courage (et pas d'urgence pour moi)

**Comment by franck-paul** [comment]
Je viens de publier une 1.2.1 qui règle l'erreur 500, mais il reste encore pas mal à faire sur cette usine à gaz !

**Comment by franck-paul** [comment]
Visiblement le sparadrap a l'air d'avoir suffit, je ferme
